# Generated by Django 5.2.7 on 2025-10-03 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in a valid format with 7-20 characters.', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')]),
        ),
    ]
